[versions]
kotlin = "2.2.21"
jvm = { strictly = "23" }

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

#Build Conventions
kevlarConventions-kotlin-jvm = { id = "kevlarConventions.kotlin.jvm" }
kevlarConventions-kotlin-test = { id = "kevlarConventions.kotlin.test" }
kevlarConventions-kotlin-repositories = { id = "kevlarConventions.kotlin.repositories" }